SET C51INC=F:\keil\C51\Inc
SET C51LIB=F:\keil\C51\Lib
SET CPU_TYPE=OB38R08T1
SET CPU_VENDOR=On-Bright
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00F42400
"F:\keil\C51\BIN\A51.EXE" @".\Objects\STARTU~1._IA"
"F:\keil\C51\BIN\C51.EXE" @".\Objects\main.__i"
"F:\keil\C51\BIN\C51.EXE" @".\Objects\WDT.__i"
"F:\keil\C51\BIN\C51.EXE" @".\Objects\UART0.__i"
"F:\keil\C51\BIN\C51.EXE" @".\Objects\Timer.__i"
